### PR TITLE
Lps 66911

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Hey @shuyangzhou I'm getting an intermittent exception when I run tests on this PR:

```
java.lang.Exception
	at org.eclipse.equinox.http.servlet.internal.registration.Registration.destroy(Registration.java:45)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.destroy(EndpointRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.removedService(ContextServletTrackerCustomizer.java:88)
	at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.removedService(ContextServletTrackerCustomizer.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:967)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
	at org.osgi.util.tracker.ServiceTracker.close(ServiceTracker.java:377)
	at org.eclipse.equinox.http.servlet.internal.context.ContextController.destroy(ContextController.java:587)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl.removedService(HttpServiceRuntimeImpl.java:321)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl.removedService(HttpServiceRuntimeImpl.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:967)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:909)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:915)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:222)
	at org.eclipse.equinox.http.servlet.tests.DispatchingTest.tearDown(DispatchingTest.java:79)
	at junit.framework.TestCase.runBare(TestCase.java:146)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

```

**Comment by shuyangzhou** [comment]
@rotty3000 that's just a "debug" output in a very weird/bad way. When Registration.referenceCount is not 0, and a thread is calling Registration.destroy, it will have to wait until the count is down to 0, in the mean time, it calls ```(new Exception()).printStackTrace();```

It is not a bug, it is on purposely dumping out the stack trace, which is actually a very bad practice. And also it uses synchronized to do the basic counting syncing, it is actually on my optimize list. I will send you another pull to optimize away those unnecessary synchronized blocks soon.

**Comment by rotty3000** [comment]
@shuyangzhou I wish you would please refrain from ciritcizing other people's code without understanding what it's for! The exception being printed is to indicate that there is probably something wrong! In other word, this exception DOES NOT normally happen in the normal scenario.

**Comment by shuyangzhou** [comment]
It can happen normally. When you break point after the Registration.referenceCount got increased, then stop your tomcat, you will get it, 100% of the time.

Basically it is only a current shutdown logging while there are still ongoing request processing, to me, it is really useless logging, it could happen, and will happen. There is nothing wrong about it, why dumping out the stack?

**Comment by rotty3000** [comment]
But this is happening during normal unit test execution and it never did happen before your change!

**Comment by rotty3000** [comment]
if you revert to the HEAD of the branch you will NOT get this error during tests!

**Comment by shuyangzhou** [comment]
Most likely it is due to I removed quite a few other synchronized blocks, which were too overkilled to stop this from getting hitted.

**Comment by rotty3000** [comment]
can you fix it please?

**Comment by shuyangzhou** [comment]
If you just want the stack to go away, wait for my next pull, I will get rid of that synchronized block too. Then it will never happen again.

**Comment by rotty3000** [comment]
you cannot remove it!

**Comment by shuyangzhou** [comment]
yes, I can, I will send you the pull, you will see how it is done.

**Comment by rotty3000** [comment]
the reference counting is necessary unless you use some other form of synchronization on the service instance.

**Comment by shuyangzhou** [comment]
yes, I know, there are better ways. I will not break the logic, but will remove the synchronized block.

**Comment by rotty3000** [comment]
I'm totally fine with a better way!

**Comment by rotty3000** [comment]
I have to explain all these changes upstream as well, so I have to be sure that I understand how you changed all the synchronization.

**Comment by shuyangzhou** [comment]
yes, of course, let me send the pull out first, then I can explain better when we are looking at the same thing.

**Comment by rotty3000** [comment]
Most important I have to be able to convince the upstream developers that concurrency protection of the destroy phase is still working.

**Comment by shuyangzhou** [comment]
Yes, of course, I can explain in detail to you with the code.

**Comment by shuyangzhou** [comment]
there will still be a necessary synchronization, but optimized for read. means reads will be a lot faster, writes (destroy) will be slower. It is better, because you do tons of reads, only 1 destroy.

**Comment by rotty3000** [comment]
Everyone will be very happy if it performs better under contention that's for sure.. but I need proof somehow... a test would be best.

**Comment by rotty3000** [comment]
.. sorry, proof that it didn't break.

**Comment by shuyangzhou** [comment]
Let me sending out the code change to you first, if you still feel a test is necessary after reading the code. I can do it after.

**Comment by rotty3000** [comment]
thank you for all these optimizations! I will make an attempt to forward port to master.

**Comment by shuyangzhou** [comment]
Ok, sent out https://github.com/rotty3000/rt.equinox.bundles/pull/11

**Comment by shuyangzhou** [comment]
Thanks @rotty3000 ! Let me know if you need explanation, or you feel a test is needed.

**Comment by rotty3000** [comment]
I will close all the earlier PRs

**Comment by shuyangzhou** [comment]
Please ping me on skype if you need any explanation.

**Pull request closed without merging**
