### PR TITLE
LPS-108112 / Bug 487627

### PR DESCRIPTION
**Pull request by ChrisKian**
Cherry pick was not clean, but I believe I've copied the required logic for the solution to work.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
@ChrisKian so this doesn't compile right?

**Comment by ChrisKian** [comment]
Hi @rotty3000,

I force pushed some changes, so it should compile now.  I'm not entirely sure how to do so on my own.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
So this code still does not compile! How are you sure that this fixes the bug in Liferay if this doesn't compile?

**Pull request closed without merging**
