### PR TITLE
LPS-77696

### PR DESCRIPTION
**Pull request by holatuwol**
Builds on top of the changes suggested in https://github.com/rotty3000/rt.equinox.bundles/pull/21. Please see [LPS-77696](https://issues.liferay.com/browse/LPS-77696) for additional details for this specific issue.

### CODE REVIEW

**Comment by rotty3000** [comment]
Hey @holatuwol @shuyangzhou I had managed to get all the changes (before this last one) merged upstream into the master branch and was going to backport those to our maintenance branch but got caught up in other work. I'll try to get this done by end of next week (this week I'm traveling).

Thanks for your patience.

**Comment by holatuwol** [comment]
@rotty3000 I'm going to update this fix with a slight performance improvement and force-push. Will let you know when that's finished.

**Comment by holatuwol** [comment]
@rotty3000 Force push completed.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by holatuwol** [comment]
This introduced a regression, resent with a fix under https://github.com/rotty3000/rt.equinox.bundles/pull/23.

**Pull request closed without merging**
